"""empty message

Revision ID: 6f7fdcdfe802
Revises: 
Create Date: 2024-05-25 18:58:02.703420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7fdcdfe802'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    with op.batch_alter_table('db_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_registration', schema=None) as batch_op:
        batch_op.drop_column('primary_notes')

    op.create_table('observations',
    sa.Column('pkey', sa.INTEGER(), nullable=False),
    sa.Column('fkey', sa.INTEGER(), nullable=True),
    sa.Column('sbp', sa.INTEGER(), nullable=True),
    sa.Column('dbp', sa.INTEGER(), nullable=True),
    sa.Column('hr', sa.INTEGER(), nullable=True),
    sa.Column('rr', sa.INTEGER(), nullable=True),
    sa.Column('spo2', sa.INTEGER(), nullable=True),
    sa.Column('gcs', sa.INTEGER(), nullable=True),
    sa.Column('temp', sa.INTEGER(), nullable=True),
    sa.Column('cap_refill', sa.VARCHAR(), nullable=True),
    sa.Column('l_pupil_size', sa.INTEGER(), nullable=True),
    sa.Column('r_pupil_size', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fkey'], ['db_registration.id'], ),
    sa.PrimaryKeyConstraint('pkey')
    )
    # ### end Alembic commands ###
